# Generated by Django 5.1.4 on 2024-12-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deudas', models.CharField(choices=[('Crédito Consumo', 'Crédito Consumo'), ('Crédito Hipotecario', 'Crédito Hipotecario'), ('Deuda Universitaria', 'Deuda Universitaria'), ('Compra en crédito', 'Compra en crédito'), ('Prestamos', 'Prestamos'), ('Otros', 'Otros')], max_length=20)),
                ('fuente', models.CharField(choices=[('Cta Bancaria', 'Cta Bancaria'), ('Efectivo', 'Efectivo')], max_length=15)),
                ('fecha_deuda', models.DateField()),
                ('valor_deuda', models.IntegerField()),
                ('cuotas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.CharField(choices=[('Servicios Básicos', 'Servicios Básicos'), ('Necesidades', 'Necesidades'), ('Mascotas', 'Mascotas'), ('Compra en crédito', 'Compra en crédito'), ('Prestamos', 'Prestamos'), ('Caprichos', 'Caprichos'), ('Otros', 'Otros')], max_length=20)),
                ('fuente', models.CharField(choices=[('Cta Bancaria', 'Cta Bancaria'), ('Efectivo', 'Efectivo')], max_length=15)),
                ('fecha_gasto', models.DateField()),
                ('valor_gasto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('Sueldo', 'Sueldo'), ('Otro', 'Otro')], max_length=6)),
                ('tipo', models.CharField(choices=[('Cta Bancaria', 'Cta Bancaria'), ('Efectivo', 'Efectivo')], max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('valor_ingreso', models.IntegerField()),
            ],
        ),
    ]
