# Generated by Django 5.1.4 on 2024-12-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deuda',
            name='fuente',
        ),
        migrations.AddField(
            model_name='deuda',
            name='entidad',
            field=models.CharField(choices=[('Itau', 'Itau'), ('Scotiabank', 'Scotiabank'), ('Familia', 'Familia')], default='Itau', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deuda',
            name='deudas',
            field=models.CharField(choices=[('Crédito Consumo', 'Crédito Consumo'), ('Crédito Hipotecario', 'Crédito Hipotecario'), ('Compra en crédito', 'Compra en crédito'), ('Prestamos', 'Prestamos'), ('Otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='egresos',
            name='fuente',
            field=models.CharField(choices=[('Itau', 'Itau'), ('Scotiabank', 'Scotiabank')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='tipo',
            field=models.CharField(choices=[('Cta Corriente', 'Cuenta Corriente'), ('Efectivo', 'Efectivo')], max_length=15),
        ),
    ]
