# Generated by Django 5.1.4 on 2025-01-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_deuda_entidad_alter_egresos_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='cuotas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='entidad',
            field=models.CharField(choices=[('Itau', 'Itau'), ('Scotiabank', 'Scotiabank'), ('Particulares', 'Particulares'), ('Otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='valor_deuda',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='egresos',
            name='valor_gasto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='valor_ingreso',
            field=models.PositiveIntegerField(),
        ),
    ]
