# Generated by Django 5.1.4 on 2025-01-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_deuda_usuario_ingresos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deuda',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='egresos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='usuario',
        ),
    ]
